apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-flask-app-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: basic-flask-app-demo
  template:
    metadata:
      labels:
        app: basic-flask-app-demo
    spec:
      containers:
        - name: basic-flask-app-demo
          image: x64nik/basic-flask-app:basic-flask-app
          ports:
            - containerPort: 5050
          env:
            - name: PORT
              value: "5050"
---
apiVersion: v1
kind: Service
metadata:
  name: basic-flask-app-demo
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5050
  selector:
    app: basic-flask-app-demo
