version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Check 01
          command: whoami

      - run:
          name: Check 02
          command: ls -la

      - run:
          name: Check 03
          command: ip a

      - run:
          name: Check 04
          command: cat /etc/os-release

      - run:
          name: Check 05
          command: uname -r

      - run:
          name: Check 06
          command: ping -c 3 rushikesh.de

workflows:
  say-hello-workflow:
    jobs:
      - build
