version: 2.1

jobs:
  test-build-01:
    docker:
      - image:  cimg/base:stable

    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo 'python3 saying hello'" 
       
      - run:
          name: "check python3"
          command: "which python3 && python3 --version"

      - run:
          name: "install pip3"
          command: "apt-get install pip3"


      - run:
          name: "install pip flask"
          command: "pip3 install flask"



# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test-build-01-workflow:
    jobs:
      - test-build-01