version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Check 01
          command: echo "hlo"

workflows:
  say-hello-workflow:
    jobs:
      - build
